name: Python CI

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: "3.10" }
      - run: pip install -r venv_demo/requirements.txt
      - run: flake8 .
      - run: pytest -q
