pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh 'python3 -m venv .venv'
                sh '.venv/bin/pip install -r venv_demo/requirements.txt'
            }
        }
        stage('Lint') {
            steps {
                sh '.venv/bin/flake8 .'
            }
        }
        stage('Test') {
            steps {
                sh '.venv/bin/pytest -q'
            }
        }
    }
}
